apiVersion: v1
kind: Service
metadata:
  name: minio-data
  namespace: {{ .Values.namespace }}
  labels:
    app: minio
spec:
  type: {{ .Values.minio.serviceData.type }}
  selector:
    app: minio
  ports:
  - protocol: TCP
    port: {{ .Values.minio.serviceData.port }}
    targetPort: {{ .Values.minio.apiPort }}
