apiVersion: v1
kind: Service
metadata:
  name: minio-ui
  namespace: {{ .Values.namespace }}
  labels:
    app: minio
spec:
  type: {{ .Values.minio.serviceUI.type }}
  selector:
    app: minio
  ports:
  - protocol: TCP
    port: {{ .Values.minio.serviceUI.port }}
    targetPort: {{ .Values.minio.consolePort }}
    {{- if eq .Values.minio.serviceUI.type "NodePort" }}
    nodePort: {{ .Values.minio.serviceUI.nodePort }}
    {{- end }}
