apiVersion: apps/v1
kind: Deployment
metadata:
  name: aigw-ui
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aigw-ui
  template:
    metadata:
      labels:
        app: aigw-ui
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: aigw-ui
          image: {{ .Values.aigwUi.image }}
          ports:
            - containerPort: {{ .Values.aigwUi.port }}
          volumeMounts:
            - name: configs-volume
              mountPath: /usr/src/app/configs
          env:
            - name: NODE_ENV
              value: {{ .Values.aigwUi.env.nodeEnv | quote }}
            - name: K8S_SERVICE_ACCOUNT_TOKEN
              value: {{ .Values.aigwUi.env.k8sServiceAccountToken | quote }}
            - name: K8S_NAMESPACE
              value: {{ .Values.aigwUi.env.k8sNamespace | quote }}
            - name: K8S_CONFIGMAP_NAME
              value: {{ .Values.aigwUi.env.k8sConfigmapName | quote }}
            - name: K8S_DEPLOYMENT_NAME
              value: {{ .Values.aigwUi.env.k8sDeploymentName | quote }}
            - name: CONFIGS_DIR
              value: {{ .Values.aigwUi.env.configsDir | quote }}
            - name: S3_ENDPOINT
              value: {{ .Values.aigwUi.env.s3Endpoint | quote }}
            - name: S3_ACCESS_KEY
              value: {{ .Values.aigwUi.env.s3AccessKey | quote }}
            - name: S3_SECRET_KEY
              value: {{ .Values.aigwUi.env.s3SecretKey | quote }}
            - name: S3_BUCKET_NAME
              value: {{ .Values.aigwUi.env.s3BucketName | quote }}
      volumes:
        - name: configs-volume
          hostPath:
            path: {{ .Values.aigwUi.storage.hostPath }}
            type: DirectoryOrCreate
